language: node_js
node_js:
- '0.10'
- '0.12'
addons:
  sauce_connect: true
script: gulp test:saucelabs
env:
  global:
  - secure: mHZ6pPMJFw73VBLy3JkXfvBOyLIIkT6SSs7qrLseM8zsh3ivQ8720S5pLgpX7hNGmETS+JPnVib9IoNBCJDiAw84T+FFzhOd0w2zpcYlAPCVjQfT8RCTP2yiiwRdWA/tcngu/fRCi33NjB7t6C+ZAQGxOj8a73rsb2VNbhToiYM=
  - secure: b+kZKTkMlXzY7naPksutBIciAmGI+UnvzkGyEaGXnErtNuzPcms2PQmdIY5YLs9WsnKz+aA+cBlc02IlldwXE7kHE9pqwOsfFS7LFzMJDAAy6Nxcj5hcG/EQyPr9FqRBKO3coq9yjIPkEkv24quaq88klxLz5MhnSKDFoJJqRXc=
